# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "kashiwamochi"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mashiro"]
  s.date = "2011-10-27"
  s.description = "Minimal searchng extension for Rails 3"
  s.email = "mail@mashiro.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "kashiwamochi.gemspec",
    "lib/kashiwamochi.rb",
    "lib/kashiwamochi/action_view_extension.rb",
    "lib/kashiwamochi/configuration.rb",
    "lib/kashiwamochi/query.rb",
    "lib/kashiwamochi/railtie.rb",
    "lib/kashiwamochi/search.rb",
    "lib/kashiwamochi/sort.rb",
    "spec/kashiwamochi/action_view_extension_spec.rb",
    "spec/kashiwamochi/config_spec.rb",
    "spec/kashiwamochi/query_spec.rb",
    "spec/kashiwamochi/sort_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/mashiro/kashiwamochi"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Minimal searching extension for Rails 3"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<railties>, ["~> 3.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<railties>, ["~> 3.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<railties>, ["~> 3.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

